### ISSUE TITLE
Catch the "Close must be last decision in list" in Decider,  

### ISSUE THREAD

**Issue by anthonime** [solambda/swiffer#26]
... so that the decider does not stop!

And log this as a WARNING.

**Comment by akurlykov** [comment]
**Integration test results**
DecisionTypes which could be scheduled together with all the close decisions:
- RecordMarker,
- StartChildWorkflowExecution,
- RequestCancelExternalWorkflowExecution;

Not tested (not implemented in Decisions):
- RequestCancelActivityTask,
- SignalExternalWorkflowExecution,
- ScheduleLambdaFunction
